"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$("#graph"),ctx=canvas.getContext("2d");
const state={mode:"teach",a:1,h:1,k:-3,showVertex:true,showAxis:true,showPairs:true,gStep:0,tStep:0,algebraStep:0,standard:{a:1,b:-2,c:-3},score:0,skills:{"Read the graph":[0,0],"Vertex and axis":[0,0],"Maximum or minimum":[0,0],"Graph from an equation":[0,0]}};
const fmt=n=>n<0?"−"+Math.abs(n):String(n), close=(x,y)=>Math.abs(Number(x)-y)<.01;
const nice=n=>fmt(Math.abs(n)<1e-10?0:Math.round(n*100)/100);
function roots(){const d=-state.k/state.a;if(d<0)return[];if(Math.abs(d)<1e-10)return[state.h];const r=Math.sqrt(d);return[state.h-r,state.h+r]}
function equation(a=state.a,h=state.h,k=state.k){const ac=a===1?"":a===-1?"−":fmt(a);return `f(x) = ${ac}(x ${h>=0?"−":"+"} ${Math.abs(h)})² ${k>=0?"+":"−"} ${Math.abs(k)}`}
function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,2),box=canvas.getBoundingClientRect(),w=Math.max(320,Math.round(box.width)),h=Math.min(620,Math.max(340,Math.round(w*.78)));canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.height=h+"px";ctx.setTransform(dpr,0,0,dpr,0,0);draw(w,h)}
function draw(w=canvas.clientWidth,h=parseFloat(canvas.style.height)||620){ctx.clearRect(0,0,w,h);const pad=42,xmin=-8,xmax=8,ymin=-8,ymax=8,sx=(w-2*pad)/(xmax-xmin),sy=(h-2*pad)/(ymax-ymin),X=x=>pad+(x-xmin)*sx,Y=y=>h-pad-(y-ymin)*sy;
  ctx.fillStyle="#fbfcfd";ctx.fillRect(0,0,w,h);ctx.lineWidth=1;ctx.strokeStyle="#e1e4e7";ctx.font="12px system-ui";ctx.textAlign="center";ctx.textBaseline="top";
  for(let x=xmin;x<=xmax;x++){ctx.beginPath();ctx.moveTo(X(x),pad);ctx.lineTo(X(x),h-pad);ctx.stroke();if(x!==0){ctx.fillStyle="#737983";ctx.fillText(fmt(x),X(x),Y(0)+7)}}
  ctx.textAlign="right";ctx.textBaseline="middle";for(let y=ymin;y<=ymax;y++){ctx.beginPath();ctx.moveTo(pad,Y(y));ctx.lineTo(w-pad,Y(y));ctx.stroke();if(y!==0){ctx.fillStyle="#737983";ctx.fillText(fmt(y),X(0)-7,Y(y))}}
  ctx.strokeStyle="#2a2e34";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(pad,Y(0));ctx.lineTo(w-pad,Y(0));ctx.moveTo(X(0),pad);ctx.lineTo(X(0),h-pad);ctx.stroke();ctx.fillStyle="#2a2e34";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("x",w-pad+14,Y(0));ctx.fillText("y",X(0),pad-14);
  if(state.showAxis){ctx.save();ctx.setLineDash([8,7]);ctx.strokeStyle="#b5121b";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(X(state.h),pad);ctx.lineTo(X(state.h),h-pad);ctx.stroke();ctx.restore();ctx.fillStyle="#8e0e15";ctx.textAlign="left";ctx.fillText(`x = ${fmt(state.h)}`,Math.min(X(state.h)+7,w-75),pad+14)}
  ctx.strokeStyle="#1677a7";ctx.lineWidth=4;ctx.lineJoin="round";ctx.beginPath();let started=false;for(let px=pad;px<=w-pad;px+=1){const x=xmin+(px-pad)/sx,y=state.a*(x-state.h)**2+state.k,py=Y(y);if(py>=pad-20&&py<=h-pad+20){if(!started){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py)}else started=false}ctx.stroke();
  if(state.showPairs){const dx=Math.min(2,Math.sqrt(Math.max(.5,6/Math.abs(state.a||.5)))),yv=state.a*dx*dx+state.k;[[state.h-dx,yv],[state.h+dx,yv]].forEach(([x,y])=>{if(y>=ymin&&y<=ymax){ctx.fillStyle="#e9a23b";ctx.beginPath();ctx.arc(X(x),Y(y),6,0,Math.PI*2);ctx.fill()}})}
  roots().forEach((r,i,all)=>{if(r>=xmin&&r<=xmax){ctx.fillStyle="#7b3fc6";ctx.beginPath();ctx.arc(X(r),Y(0),7,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke();ctx.fillStyle="#553080";ctx.font="bold 12px system-ui";ctx.textAlign=all.length===2&&i===0?"right":"left";ctx.textBaseline="bottom";ctx.fillText(`(${nice(r)}, 0)`,X(r)+(all.length===2&&i===0?-9:9),Y(0)-9)}})
  if(state.showVertex){ctx.fillStyle="#b5121b";ctx.beginPath();ctx.arc(X(state.h),Y(state.k),7,0,Math.PI*2);ctx.fill();ctx.fillStyle="#17191d";ctx.textAlign=state.h>4?"right":"left";ctx.textBaseline=state.k>5?"top":"bottom";ctx.font="bold 13px system-ui";ctx.fillText(`(${nice(state.h)}, ${nice(state.k)})`,X(state.h)+(state.h>4?-10:10),Y(state.k)+(state.k>5?10:-10))}
}
function setGraph(a,h,k){state.a=a;state.h=h;state.k=k;draw();updateReadouts()}
function updateReadouts(){const type=state.a>0?"Minimum":"Maximum",rs=roots(),rootText=rs.length===0?"No real roots":rs.length===1?`x = ${nice(rs[0])}`:`x ≈ ${nice(rs[0])} and x ≈ ${nice(rs[1])}`;$("#vertex-readout").textContent=`(${nice(state.h)}, ${nice(state.k)})`;$("#axis-readout").textContent=`x = ${nice(state.h)}`;$("#direction-readout").textContent=state.a>0?"Opens up":"Opens down";$("#extremum-readout").textContent=`${type}: ${nice(state.k)}`;$("#roots-readout").textContent=rootText;$("#strip-vertex").textContent=`(${nice(state.h)}, ${nice(state.k)})`;$("#strip-axis").textContent=`x = ${nice(state.h)}`;$("#strip-value").textContent=nice(state.k);$("#teach-insight").textContent=`The vertex is the ${state.a>0?"lowest":"highest"} point.`;$("#teach-detail").textContent=`Its y-coordinate, ${nice(state.k)}, is the ${type.toLowerCase()} value.`;$("#graph-announce").textContent=`Graph of ${equation()}. Vertex ${state.h}, ${state.k}. Axis x equals ${state.h}. ${type} value ${state.k}. ${rootText}.`}
function updateEquation(){const {a,h,k}=state;$("#eq-a").textContent=a===1?"":a===-1?"−":fmt(a);$("#eq-h-sign").textContent=h>=0?"−":"+";$("#eq-h").textContent=Math.abs(h);$("#eq-k-sign").textContent=k>=0?"+":"−";$("#eq-k").textContent=Math.abs(k);$("#a-output").textContent=fmt(a);$("#h-output").textContent=fmt(h);$("#k-output").textContent=fmt(k);updateReadouts();draw()}
function mode(name){state.mode=name;$$('.mode-tab').forEach(b=>{const on=b.dataset.mode===name;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});$$('.panel-view').forEach(p=>p.classList.remove('active'));$(`#${name}-panel`).classList.add('active');const labels={teach:['Explore the structure','Watch the equation and graph change together'],algebra:['Build the vertex algebraically','Connect standard form to the graph'],guided:['Work one step at a time','Use the graph to support each step'],test:['Independent skill check','Analyze the graph and equation']};$("#mode-label").textContent=labels[name][0];$("#graph-title").textContent=labels[name][1];if(name==='algebra')startAlgebra();if(name==='guided')startGuided();if(name==='test')startTest();setTimeout(resizeCanvas,0)}
function signedTerm(n,variable=''){return `${n>=0?'+':'−'} ${Math.abs(n)}${variable}`}
function updateStandard(){let a=Number($("#standard-a").value),b=Number($("#standard-b").value),c=Number($("#standard-c").value);if(!Number.isFinite(a)||a===0){a=1;$("#standard-a").value=1}if(!Number.isFinite(b))b=0;if(!Number.isFinite(c))c=0;state.standard={a,b,c};state.a=a;state.h=-b/(2*a);state.k=a*state.h**2+b*state.h+c;$("#std-a").textContent=fmt(a);$("#std-b-sign").textContent=b>=0?'+':'−';$("#std-b").textContent=Math.abs(b);$("#std-c-sign").textContent=c>=0?'+':'−';$("#std-c").textContent=Math.abs(c);state.algebraStep=0;renderAlgebra();updateReadouts();draw()}
function startAlgebra(){const s=state.standard;$("#standard-a").value=s.a;$("#standard-b").value=s.b;$("#standard-c").value=s.c;updateStandard()}
function renderAlgebra(){const {a,b,c}=state.standard,h=state.h,k=state.k,type=a>0?'minimum':'maximum';$("#work-axis").innerHTML=`x = <span class="fraction"><span>−b</span><span>2a</span></span> = <span class="fraction"><span>−(${nice(b)})</span><span>2(${nice(a)})</span></span> = ${nice(h)}`;$("#work-line").textContent=`Axis of symmetry: x = ${nice(h)}`;$("#work-substitute").innerHTML=`f(${nice(h)}) = ${nice(a)}(${nice(h)})² ${signedTerm(b,`(${nice(h)})`)} ${signedTerm(c)} = ${nice(k)}`;$("#work-vertex").innerHTML=`Vertex: (${nice(h)}, ${nice(k)})<br>${a>0?'Because a > 0, the graph opens upward.':'Because a < 0, the graph opens downward.'}<br>The ${type} value is ${nice(k)}.`;$$('.algebra-step').forEach((el,i)=>{el.classList.toggle('revealed',i<state.algebraStep);el.classList.toggle('active',i===state.algebraStep&&state.algebraStep<4);el.classList.toggle('locked',i>state.algebraStep)});$("#algebra-next").hidden=state.algebraStep>=4;$("#algebra-next").textContent=`Show step ${Math.min(state.algebraStep+1,4)}`;const rs=roots();$("#root-note").textContent=rs.length===0?'This graph does not cross the x-axis, so it has no real roots.':rs.length===1?`The graph touches the x-axis at the root (${nice(rs[0])}, 0).`:`The purple points mark the roots (${nice(rs[0])}, 0) and (${nice(rs[1])}, 0).`}
const guided=[
 {skill:"Read the graph",q:"Does the parabola have a maximum or minimum?",kind:"choices",choices:["Maximum","Minimum"],answer:s=>s.a>0?"Minimum":"Maximum",why:s=>`It opens ${s.a>0?'upward':'downward'}, so the vertex is the ${s.a>0?'lowest':'highest'} point.`},
 {skill:"Locate the vertex",q:"Enter the coordinates of the vertex.",kind:"coord",answer:s=>[s.h,s.k],why:s=>`The turning point is (${fmt(s.h)}, ${fmt(s.k)}).`},
 {skill:"Name the symmetry line",q:"What is the axis of symmetry?",kind:"x",answer:s=>s.h,why:s=>`The vertical line through the vertex is x = ${fmt(s.h)}.`},
 {skill:"Separate point from value",q:"What is the maximum or minimum value?",kind:"number",answer:s=>s.k,why:s=>`The value is the y-coordinate of the vertex: ${fmt(s.k)}. The point is (${fmt(s.h)}, ${fmt(s.k)}).`},
 {skill:"Connect equation and graph",q:"Which vertex form matches this graph?",kind:"equations",answer:s=>equation(s.a,s.h,s.k),why:s=>`Vertex form shows h = ${fmt(s.h)} and k = ${fmt(s.k)} directly.`}
];
function randomGraph(){let a=[-2,-1,-.5,.5,1,2][Math.floor(Math.random()*6)],h=Math.floor(Math.random()*7)-3,k=Math.floor(Math.random()*7)-3;setGraph(a,h,k)}
function renderControl(item,prefix){let html='';if(item.kind==='choices'){html='<div class="choice-grid">'+item.choices.map((c,i)=>`<div class="choice"><input type="radio" name="${prefix}" id="${prefix}-${i}" value="${c}"><label for="${prefix}-${i}">${c}</label></div>`).join('')+'</div>'}else if(item.kind==='coord'){html=`<div class="coordinate-answer"><span>(</span><input aria-label="x-coordinate" inputmode="decimal"><span>,</span><input aria-label="y-coordinate" inputmode="decimal"><span>)</span></div>`}else if(item.kind==='x'){html='<label class="text-answer">x = <input aria-label="Axis of symmetry value" inputmode="decimal"></label>'}else if(item.kind==='number'){html='<label class="text-answer"><span>Value:</span><input aria-label="Maximum or minimum value" inputmode="decimal"></label>'}else if(item.kind==='equations'){const correct=equation(),wrong=[equation(-state.a,state.h,state.k),equation(state.a,-state.h,state.k),equation(state.a,state.h,-state.k)].filter((v,i,a)=>a.indexOf(v)===i&&v!==correct);const opts=[correct,...wrong.slice(0,3)].sort(()=>Math.random()-.5);html='<div class="choice-grid">'+opts.map((c,i)=>`<div class="choice"><input type="radio" name="${prefix}" id="${prefix}-${i}" value="${c}"><label for="${prefix}-${i}">${c}</label></div>`).join('')+'</div>'}return html}
function getResponse(container,item,prefix){if(['choices','equations'].includes(item.kind)){const el=container.querySelector(`input[name="${prefix}"]:checked`);return el?el.value:null}const ins=[...container.querySelectorAll('input')];return item.kind==='coord'?ins.map(i=>i.value):ins[0]?.value}
function isCorrect(item,r){const ans=item.answer(state);return item.kind==='coord'?r&&close(r[0],ans[0])&&close(r[1],ans[1]):item.kind==='choices'||item.kind==='equations'?r===ans:close(r,ans)}
function startGuided(){state.gStep=0;randomGraph();renderGuided()}
function renderGuided(){const item=guided[state.gStep];$("#guided-count").textContent=`${state.gStep+1} of ${guided.length}`;$("#guided-progress").style.width=`${(state.gStep+1)/guided.length*100}%`;$("#guided-skill").textContent=`Step ${state.gStep+1} · ${item.skill}`;$("#guided-title").textContent=item.q;$("#guided-control").innerHTML=renderControl(item,'guided-answer');$("#guided-feedback").className='feedback';$("#guided-feedback").textContent='';$("#guided-check").hidden=false;$("#guided-next").hidden=true;$("#guided-next").textContent=state.gStep===guided.length-1?'Try another graph ↻':'Next step →'}
function checkGuided(){const item=guided[state.gStep],r=getResponse($("#guided-control"),item,'guided-answer'),ok=isCorrect(item,r),f=$("#guided-feedback");f.className=`feedback ${ok?'correct':'incorrect'}`;f.innerHTML=ok?`<strong>Yes.</strong> ${item.why(state)}`:`<strong>Not yet.</strong> Look at the vertex and the direction the graph opens, then try again.`;if(ok){$("#guided-check").hidden=true;$("#guided-next").hidden=false}}
const testBank=[
 {skill:"Vertex and axis",type:"Identify the vertex",q:"Enter the coordinates of the vertex.",kind:"coord",answer:s=>[s.h,s.k],why:s=>`The vertex is (${fmt(s.h)}, ${fmt(s.k)}).`},
 {skill:"Vertex and axis",type:"Identify the axis",q:"Identify the axis of symmetry.",kind:"x",answer:s=>s.h,why:s=>`The axis is x = ${fmt(s.h)}.`},
 {skill:"Maximum or minimum",type:"Classify the extremum",q:"Does this function have a maximum or minimum?",kind:"choices",choices:["Maximum","Minimum"],answer:s=>s.a>0?"Minimum":"Maximum",why:s=>`The graph opens ${s.a>0?'up':'down'}, so it has a ${s.a>0?'minimum':'maximum'}.`},
 {skill:"Maximum or minimum",type:"Identify the value",q:"What is the maximum or minimum value?",kind:"number",answer:s=>s.k,why:s=>`The extremum value is ${fmt(s.k)}, the y-coordinate of the vertex.`},
 {skill:"Read the graph",type:"Read the direction",q:"Which direction does this parabola open?",kind:"choices",choices:["Upward","Downward"],answer:s=>s.a>0?"Upward":"Downward",why:s=>`The branches point ${s.a>0?'upward':'downward'}.`},
 {skill:"Graph from an equation",type:"Match vertex form",q:"Which equation matches the graph?",kind:"equations",answer:s=>equation(s.a,s.h,s.k),why:s=>`${equation()} has vertex (${fmt(s.h)}, ${fmt(s.k)}).`},
 {skill:"Graph from an equation",type:"Interpret a",q:"For this graph, is the leading coefficient a positive or negative?",kind:"choices",choices:["Positive","Negative"],answer:s=>s.a>0?"Positive":"Negative",why:s=>`Opening ${s.a>0?'up':'down'} means a is ${s.a>0?'positive':'negative'}.`},
 {skill:"Read the graph",type:"Point versus value",q:"Which answer gives the extremum point, not only its value?",kind:"choices",choices:[],answer:s=>`(${fmt(s.h)}, ${fmt(s.k)})`,why:s=>`The point needs both coordinates: (${fmt(s.h)}, ${fmt(s.k)}).`}
];
function testItems(){return testBank.map(x=>({...x})).sort(()=>Math.random()-.5)}let currentTests=[];
function startTest(){state.tStep=0;state.score=0;Object.keys(state.skills).forEach(k=>state.skills[k]=[0,0]);currentTests=testItems();$("#test-active").hidden=false;$("#test-results").hidden=true;randomGraph();renderTest()}
function renderTest(){const item=currentTests[state.tStep];if(item.type==='Point versus value')item.choices=[`(${fmt(state.h)}, ${fmt(state.k)})`,fmt(state.k),`x = ${fmt(state.h)}`,`(${fmt(state.k)}, ${fmt(state.h)})`];$("#test-count").textContent=`${state.tStep+1} of ${currentTests.length}`;$("#test-progress").style.width=`${(state.tStep+1)/currentTests.length*100}%`;$("#test-type").textContent=item.type;$("#test-title").textContent=item.q;$("#test-control").innerHTML=renderControl(item,'test-answer');$("#test-feedback").className='feedback';$("#test-feedback").textContent='';$("#test-check").hidden=false;$("#test-next").hidden=true;$("#test-next").textContent=state.tStep===currentTests.length-1?'See results →':'Next →'}
function checkTest(){const item=currentTests[state.tStep],r=getResponse($("#test-control"),item,'test-answer');if(r===null||r===''||(Array.isArray(r)&&r.some(v=>v===''))){const f=$("#test-feedback");f.className='feedback incorrect';f.textContent='Enter or select an answer first.';return}const ok=isCorrect(item,r),f=$("#test-feedback");state.skills[item.skill][1]++;if(ok){state.score++;state.skills[item.skill][0]++}f.className=`feedback ${ok?'correct':'incorrect'}`;f.innerHTML=`<strong>${ok?'Correct.':'Review this one.'}</strong> ${item.why(state)}`;$("#test-check").hidden=true;$("#test-next").hidden=false}
function finishTest(){const pct=Math.round(state.score/currentTests.length*100);$("#test-active").hidden=true;$("#test-results").hidden=false;$("#score-value").textContent=pct+'%';$("#score-ring").style.background=`conic-gradient(var(--red) ${pct}%,#e6e8eb ${pct}%)`;$("#skill-results").innerHTML=Object.entries(state.skills).filter(([,v])=>v[1]).map(([k,[n,d]])=>{const p=Math.round(n/d*100);return `<div class="skill-result"><div><span>${k}</span><strong>${n} of ${d}</strong></div><div class="mini-track"><span style="width:${p}%"></span></div></div>`}).join('')}
$$('.mode-tab').forEach(b=>b.addEventListener('click',()=>mode(b.dataset.mode)));['a','h','k'].forEach(v=>$(`#${v}-slider`).addEventListener('input',e=>{let n=Number(e.target.value);if(v==='a'&&n===0){n=.5;e.target.value=n}state[v]=n;updateEquation()}));[['show-vertex','showVertex'],['show-axis','showAxis'],['show-pairs','showPairs']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=e.target.checked;draw()}));
$('#reset-btn').addEventListener('click',()=>{if(state.mode==='teach'){Object.assign(state,{a:1,h:1,k:-3});$('#a-slider').value=1;$('#h-slider').value=1;$('#k-slider').value=-3;updateEquation()}else if(state.mode==='algebra'){state.standard={a:1,b:-2,c:-3};startAlgebra()}else if(state.mode==='guided')startGuided();else startTest()});
function standardInputChanged(){
  const raw=['standard-a','standard-b','standard-c'].map(id=>$('#'+id).value.trim());
  if(raw.some(v=>v===''||v==='-'||v==='.'||v==='-.'))return;
  if(Number(raw[0])===0)return;
  updateStandard();
}
['standard-a','standard-b','standard-c'].forEach(id=>{
  $('#'+id).addEventListener('input',standardInputChanged);
  $('#'+id).addEventListener('change',updateStandard);
});
$('#algebra-next').addEventListener('click',()=>{state.algebraStep=Math.min(4,state.algebraStep+1);renderAlgebra()});
$('#algebra-reset').addEventListener('click',()=>{state.algebraStep=0;renderAlgebra()});
$('#guided-check').addEventListener('click',checkGuided);$('#guided-next').addEventListener('click',()=>{if(state.gStep===guided.length-1)startGuided();else{state.gStep++;renderGuided()}});$('#guided-restart').addEventListener('click',startGuided);$('#test-check').addEventListener('click',checkTest);$('#test-next').addEventListener('click',()=>{if(state.tStep===currentTests.length-1)finishTest();else{state.tStep++;randomGraph();renderTest()}});$('#test-restart').addEventListener('click',startTest);window.addEventListener('resize',resizeCanvas);updateEquation();resizeCanvas();
